(function(g){var window=this;var $pa=function(a,b){return g.Vb(a,b)},d5=function(){},aqa=function(a){if(a.zc&&"function"==typeof a.zc)return a.zc();
if(g.Fa(a))return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Rb(a)},bqa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||g.Fa(a))(0,g.z)(a,b,void 0);else{if(a.Hd&&"function"==typeof a.Hd)var c=a.Hd();else if(a.zc&&"function"==typeof a.zc)c=void 0;else if(g.Na(a)||g.Fa(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Sb(a);d=aqa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},e5=function(a){g.Vm(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.H)()).toString(36));
return a},f5=function(a,b,c){g.Ma(c)||(c=[String(c)]);
g.$m(a.l,b,c)},g5=function(a){return(a=g.to(a))?new ActiveXObject(a):new XMLHttpRequest},h5=function(a,b){return b+" ["+a.aa+" "+a.D+" "+a.getStatus()+"]"},cqa=function(a){return"content-type"==a.toLowerCase()},i5=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.F&&(g.v.clearTimeout(a.F),a.F=null)},dqa=function(a){return g.Md&&g.od(9)&&g.Ha(a.timeout)&&g.Ea(a.ontimeout)},j5=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},k5=function(a,b){if(a.g){i5(a);
var c=a.g,d=a.P[0]?g.Ja:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},l5=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;j5(a);k5(a)},m5=function(a){return a.g?a.g.readyState:0},n5=function(a){if(a.i&&"undefined"!=typeof g.hY)if(a.P[1]&&4==m5(a)&&2==a.getStatus())h5(a,"Local request error detected and ignored");
else if(a.C&&4==m5(a))g.Gg(a.Xv,0,a);else if(a.dispatchEvent("readystatechange"),4==m5(a)){h5(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Sg(1,String(a.D));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!eqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<m5(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";j5(a)}}finally{k5(a)}}},o5=function(a){g.Sf.call(this);
this.headers=new g.Km;this.M=a||null;this.i=!1;this.P=this.g=null;this.aa=this.D="";this.u=0;this.l="";this.o=this.W=this.C=this.O=!1;this.A=0;this.F=null;this.Z="";this.I=this.R=!1},p5=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},fqa=function(a,b){var c=[];
g.Lk(b,function(d){try{var e=g.Io.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ea(e)?g.Ho(e)&&c.push(d):c.push(d)},a);
return c},gqa=function(a,b){var c=fqa(a,b);
(0,g.z)(c,function(d){g.Io.prototype.remove.call(this,d)},a)},q5=function(a){if(a.cd){if(a.cd.locationOverrideToken)return{locationOverrideToken:a.cd.locationOverrideToken};
if(null!=a.cd.latitudeE7&&null!=a.cd.longitudeE7)return{latitudeE7:a.cd.latitudeE7,longitudeE7:a.cd.longitudeE7}}return null},hqa=function(a,b){g.ab(a,b)||a.push(b)},r5=function(a){var b=0,c;
for(c in a)b++;return b},s5=function(a,b){var c=b instanceof g.yc?b:g.Ec(b,/^data:image\//i.test(b));
a.src=g.zc(c)},iqa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},jqa=function(a,b,c,d){var e=new g.Nm(null,void 0);
a&&g.Om(e,a);b&&g.Pm(e,b);c&&g.Qm(e,c);d&&(e.i=d);return e},t5=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return iqa(a)},u5=function(){this.g=[];
this.i=[]},v5=function(a,b){g.Np[a]=!0;
var c=g.Lp();c&&c.publish.apply(c,arguments);g.Np[a]=!1},w5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Km;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",kqa(this,a.capabilities||""),lqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},kqa=function(a,b){a.capabilities.clear();
(0,g.Yd)(b.split(","),g.Sa($pa,mqa)).forEach(function(c){a.capabilities.add(c)})},lqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},x5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},y5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},z5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},nqa=function(a){return new x5(a)},A5=function(a){return g.Ma(a)?(0,g.B)(a,nqa):[]},B5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},C5=function(a){return g.Ma(a)?"["+(0,g.B)(a,B5).join(",")+"]":"null"},D5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},oqa=function(a){return(0,g.B)(a,function(b){return{key:b.id,
name:b.name}})},E5=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},F5=function(a,b){return g.Ya(a,function(c){return y5(c,b)})},G5=function(a){try{var b=(0,g.et)(),c=(0,g.dt)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},pqa=function(){var a=(0,g.dt)();
a&&gqa(a,a.g.lf(!0))},H5=function(){var a=g.gt("yt-remote-connected-devices")||[];
g.rb(a);return a},qqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.B)(a,function(d,e){return 0==e?d:d.substring(c.length)})},I5=function(a){g.ft("yt-remote-connected-devices",a,86400)},K5=function(){if(J5)return J5;
var a=g.gt("yt-remote-device-id");a||(a=D5(),g.ft("yt-remote-device-id",a,31536E3));for(var b=H5(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return J5=d},L5=function(){var a=H5(),b=K5();
g.ab(a,b);g.ht()&&g.tb(a,b);a=qqa(a);if(0==a.length)try{g.hs("remote_sid")}catch(c){}else try{g.gs("remote_sid",a.join(","),-1)}catch(c){}},M5=function(){return g.gt("yt-remote-session-browser-channel")},N5=function(){return g.gt("yt-remote-local-screens")||[]},O5=function(){g.ft("yt-remote-lounge-token-expiration",!0,86400)},rqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.B)(N5(),function(d){return d.loungeToken}),c=(0,g.B)(a,function(d){return d.loungeToken});
(0,g.jj)(c,function(d){return!g.ab(b,d)})&&O5();
g.ft("yt-remote-local-screens",a,31536E3)},sqa=function(a,b){g.ft("yt-remote-session-browser-channel",a);
g.ft("yt-remote-session-screen-id",b);var c=H5(),d=K5();g.ab(c,d)||c.push(d);I5(c);L5()},P5=function(a){a||(G5("yt-remote-session-screen-id"),G5("yt-remote-session-video-id"));
L5();a=H5();g.db(a,K5());I5(a)},R5=function(){if(!Q5){var a=g.So();
a&&(Q5=new g.Co(a))}return Q5?!!Q5.get("yt-remote-use-staging-server"):!1},S5=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},T5=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},V5=function(a){a.length?U5(a.shift(),function(){V5(a)}):W5()},tqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},U5=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},W5=function(){var a=T5();
a&&a(!1,"No cast extension found")},X5=function(){if(uqa){var a=2,b=T5(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;U5("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",W5,c)}},vqa=function(){X5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);V5(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},Y5=function(a,b,c){g.D.call(this);
this.A=null!=c?(0,g.x)(a,c):a;this.Wc=b;this.u=(0,g.x)(this.lD,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},Z5=function(){},$5=function(a,b,c,d){this.g=a;
this.l=b;this.C=c;this.A=d||1;this.o=45E3;this.ba=new g.an(this);this.i=new g.Fg;this.i.setInterval(250)},b6=function(a,b,c){a.Wh=1;
a.Yf=e5(b.clone());a.uh=c;a.u=!0;a6(a,null)},c6=function(a,b,c,d,e){a.Wh=1;
a.Yf=e5(b.clone());a.uh=null;a.u=c;e&&(a.Tz=!1);a6(a,d)},a6=function(a,b){a.Fi=(0,g.H)();
d6(a);a.Fg=a.Yf.clone();f5(a.Fg,"t",a.A);a.il=0;a.tc=a.g.lp(a.g.Qk()?b:null);0<a.Qp&&(a.Hn=new g.Al((0,g.x)(a.aB,a,a.tc),a.Qp));a.ba.ca(a.tc,"readystatechange",a.cM);var c=a.bh?g.cc(a.bh):{};a.uh?(a.lo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.tc.send(a.Fg,a.lo,a.uh,c)):(a.lo="GET",a.Tz&&!g.Od&&(c.Connection="close"),a.tc.send(a.Fg,a.lo,null,c));a.g.te(1)},k6=function(a,b,c){for(var d=!0;!a.Qg&&a.il<c.length;){var e=wqa(a,c);
if(e==e6){4==b&&(a.qg=4,f6(15),d=!1);break}else if(e==g6){a.qg=4;f6(16);d=!1;break}else h6(a,e)}4==b&&0==c.length&&(a.qg=1,f6(17),d=!1);a.xe=a.xe&&d;d||(i6(a),j6(a))},wqa=function(a,b){var c=a.il,d=b.indexOf("\n",c);
if(-1==d)return e6;c=Number(b.substring(c,d));if(isNaN(c))return g6;d+=1;if(d+c>b.length)return e6;var e=b.substr(d,c);a.il=d+c;return e},n6=function(a,b){a.Fi=(0,g.H)();
d6(a);var c=b?window.location.hostname:"";a.Fg=a.Yf.clone();g.Vm(a.Fg,"DOMAIN",c);g.Vm(a.Fg,"t",a.A);try{a.Be=new ActiveXObject("htmlfile")}catch(n){i6(a);a.qg=7;f6(22);j6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in l6)k=l6[l];else if(l in m6)k=l6[l]=m6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
l6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Sc(g.rc("b/12014412"),d+"</body></html>");a.Be.open();a.Be.write(g.Nc(c));a.Be.close();a.Be.parentWindow.m=(0,g.x)(a.tL,a);a.Be.parentWindow.d=(0,g.x)(a.Xy,a,!0);a.Be.parentWindow.rpcClose=(0,g.x)(a.Xy,a,!1);c=a.Be.createElement("DIV");a.Be.parentWindow.document.body.appendChild(c);d=g.Dc(a.Fg.toString());d=g.Zc(g.Ac(d));d=g.Sc(g.rc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Tc(c,d);a.g.te(1)},d6=function(a){a.Vs=(0,g.H)()+a.o;
o6(a,a.o)},o6=function(a,b){if(null!=a.Wi)throw Error("WatchDog timer not null");
a.Wi=p6((0,g.x)(a.DL,a),b)},q6=function(a){a.Wi&&(g.v.clearTimeout(a.Wi),a.Wi=null)},j6=function(a){a.g.Vv()||a.Qg||a.g.un(a)},i6=function(a){q6(a);
g.qf(a.Hn);a.Hn=null;a.i.stop();g.cn(a.ba);if(a.tc){var b=a.tc;a.tc=null;b.abort();b.dispose()}a.Be&&(a.Be=null)},h6=function(a,b){try{a.g.Ry(a,b),a.g.te(4)}catch(c){}},s6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;r6(a,b,function(k){k?c(!0):g.v.setTimeout(function(){s6(a,b,c,d,f)},f)})}},r6=function(a,b,c){var d=new Image;
d.onload=function(){try{t6(d),c(!0)}catch(e){}};
d.onerror=function(){try{t6(d),c(!1)}catch(e){}};
d.onabort=function(){try{t6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{t6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
s5(d,a)},t6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},u6=function(a){this.g=a;
this.i=new Z5},w6=function(a){var b=v6(a.g,a.ij,"/mail/images/cleardot.gif");
e5(b);s6(b.toString(),5E3,(0,g.x)(a.rC,a),3,2E3);a.te(1)},y6=function(a){var b=a.g.F;
if(null!=b)f6(5),b?(f6(11),x6(a.g,a,!1)):(f6(12),x6(a.g,a,!0));else if(a.Cd=new $5(a,void 0,void 0,void 0),a.Cd.bh=a.Op,b=a.g,b=v6(b,b.Qk()?a.Qj:null,a.Pp),f6(5),!g.Md||g.pd(10))f5(b,"TYPE","xmlhttp"),c6(a.Cd,b,!1,a.Qj,!1);else{f5(b,"TYPE","html");var c=a.Cd;a=!!a.Qj;c.Wh=3;c.Yf=e5(b.clone());n6(c,a)}},z6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new Z5;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},xqa=function(a,b){this.g=a;
this.map=b;this.context=null},A6=function(a){g.sf.call(this,"statevent",a)},B6=function(a,b){g.sf.call(this,"timingevent",a);
this.size=b},C6=function(a){g.sf.call(this,"serverreachability",a)},G6=function(a){D6(a);
if(3==a.g){var b=a.xk++,c=a.gm.clone();g.Vm(c,"SID",a.l);g.Vm(c,"RID",b);g.Vm(c,"TYPE","terminate");E6(a,c);b=new $5(a,a.l,b,void 0);b.Wh=2;b.Yf=e5(c.clone());s5(new Image,b.Yf.toString());b.Fi=(0,g.H)();d6(b)}F6(a)},I6=function(a){a.KC(1,0);
a.gm=v6(a,null,a.Np);H6(a)},D6=function(a){a.gg&&(a.gg.abort(),a.gg=null);
a.Sb&&(a.Sb.cancel(),a.Sb=null);a.nf&&(g.v.clearTimeout(a.nf),a.nf=null);J6(a);a.yd&&(a.yd.cancel(),a.yd=null);a.mg&&(g.v.clearTimeout(a.mg),a.mg=null)},K6=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new xqa(a.JH++,b));2!=a.g&&3!=a.g||H6(a)},H6=function(a){a.yd||a.mg||(a.mg=p6((0,g.x)(a.Wy,a),0),a.Qh=0)},N6=function(a,b){if(1==a.g){if(!b){a.xk=Math.floor(1E5*Math.random());
var c=a.xk++,d=new $5(a,"",c,void 0);d.bh=null;var e=L6(a),f=a.gm.clone();g.Vm(f,"RID",c);g.Vm(f,"CVER","1");E6(a,f);b6(d,f,e);a.yd=d;a.g=2}}else 3==a.g&&(b?M6(a,b):0==a.i.length||a.yd||M6(a))},M6=function(a,b){if(b)if(6<a.Rg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.xk-1;var d=L6(a)}else c=b.C,d=b.uh;else c=a.xk++,d=L6(a);var e=a.gm.clone();g.Vm(e,"SID",a.l);g.Vm(e,"RID",c);g.Vm(e,"AID",a.ji);E6(a,e);c=new $5(a,a.l,c,a.Qh+1);c.bh=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.yd=c;b6(c,e,d)},E6=function(a,b){if(a.Tc){var c=a.Tc.xv();
c&&g.Lb(c,function(d,e){g.Vm(b,e,d)})}},L6=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Rg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Rg?e:f-d;try{g.Lb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},O6=function(a){a.Sb||a.nf||(a.C=1,a.nf=p6((0,g.x)(a.Vy,a),0),a.Jh=0)},Q6=function(a){if(a.Sb||a.nf||3<=a.Jh)return!1;
a.C++;a.nf=p6((0,g.x)(a.Vy,a),P6(a,a.Jh));a.Jh++;return!0},x6=function(a,b,c){a.jo=c;
a.Ie=b.Af;a.A||I6(a)},J6=function(a){null!=a.Vg&&(g.v.clearTimeout(a.Vg),a.Vg=null)},P6=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},S6=function(a,b){if(2==b||9==b){var c=null;
a.Tc&&(c=null);var d=(0,g.x)(a.HM,a);c||(c=new g.Nm("//www.google.com/images/cleardot.gif"),e5(c));r6(c.toString(),1E4,d)}else f6(2);R6(a,b)},R6=function(a,b){a.g=0;
a.Tc&&a.Tc.zu(b);F6(a);D6(a)},F6=function(a){a.g=0;
a.Ie=-1;if(a.Tc)if(0==a.o.length&&0==a.i.length)a.Tc.Yo();else{g.ib(a.o);var b=g.ib(a.i);a.o.length=0;a.i.length=0;a.Tc.Yo(b)}},v6=function(a,b,c){var d=g.Wm(c);
if(""!=d.g)b&&g.Pm(d,b+"."+d.g),g.Qm(d,d.u);else{var e=window.location;d=jqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.vj&&g.Lb(a.vj,function(f,k){g.Vm(d,k,f)});
g.Vm(d,"VER",a.Rg);E6(a,d);return d},p6=function(a,b){if(!g.Oa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},f6=function(a){T6.dispatchEvent(new A6(T6,a))},U6=function(){},yqa=function(a,b){this.action=a;
this.params=b||{}},V6=function(a,b){g.D.call(this);
this.g=new g.M(this.lL,0,this);g.G(this,this.g);this.Wc=5E3;this.i=0;if(g.Oa(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Oa(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},W6=function(a,b,c){this.H=a;
this.A=b;this.l=new g.Bo;this.i=new V6(this.lM,this);this.g=null;this.fb=!1;this.u=null;this.F="";this.D=this.o=0;this.C=[];this.I=c||!1},zqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.jo,sessionId:a.g.l,arrayId:a.g.ji}},X6=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&N6(a.g),G6(a.g));a.D=0},Y6=function(a){return!!a.g&&3==a.g.g},Aqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},Z6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.Sg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Tg(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ib(a,"10.0")&&(this.i=!1))},$6=function(a,b){var c=a.g;
if(g.Ea(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.ch(c+b,{})},a7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.o,d,!0),onError:g.Sa(a.l,e),ie:g.Sa(a.u,e)};c&&(a.tb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Fq(b,a)},Bqa=function(){var a=b7;
c7();d7.push(a);e7(d7)},f7=function(a,b){c7();
var c=d7,d=Cqa(a,String(b));0==c.length?Dqa(d):(e7(c),(0,g.z)(c,function(e){e(d)}))},c7=function(){d7||(d7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ia("yt.mdx.remote.debug.handlers_",d7,void 0))},Dqa=function(a){var b=(g7+1)%50;
g7=b;h7[b]=a;i7||(i7=49==b)},e7=function(a){var b=h7;
if(b[0]){var c=g7,d=i7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.z)(a,function(f){f(e)})}while(d!=c);
h7=Array(50);g7=-1;i7=!1}},Cqa=function(a,b){var c=((0,g.H)()-Eqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},j7=function(a){g.P.call(this);
this.C=a;this.g=[]},k7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Fqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Yd)(a.g,function(f){return!!E5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=k7(a,b[d])||c;return c},Gqa=function(a,b){var c=a.g.length;
a.g=(0,g.Yd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},l7=function(a,b,c,d){g.P.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},n7=function(a){j7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;m7(this);this.info("Initializing with "+C5(this.g))},o7=function(a){if(a.g.length){var b=(0,g.B)(a.g,function(d){return d.id}),c=$6(a.l,"/pairing/get_lounge_token_batch");
a7(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.vD,a),(0,g.x)(a.uD,a))}},m7=function(a){var b=A5(N5());
b=(0,g.Yd)(b,function(c){return!c.uuid});
return Fqa(a,b)},p7=function(a,b){rqa((0,g.B)(a.g,z5));
b&&O5()},r7=function(a,b){g.P.call(this);
this.A=b;var c=g.gt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;q7("Initialized with "+g.Kg(this.g))},s7=function(a,b,c){var d=$6(a.u,"/pairing/get_screen_availability");
a7(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},t7=function(a,b){a:if(r5(b)!=r5(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(q7("Updated online screens: "+g.Kg(a.g)),a.g=b,a.N("screenChange"));Hqa(a)},u7=function(a){isNaN(a.l)||g.Kp(a.l);
a.l=g.Ip((0,g.x)(a.Wr,a),0<a.o&&a.o<(0,g.H)()?2E4:1E4)},q7=function(a){f7("OnlineScreenService",a)},v7=function(a){var b={};
(0,g.z)(a.A(),function(c){c.token?b[c.token]=c.id:this.Hb("Requesting availability of screen w/o lounge token.")});
return b},Hqa=function(a){a=g.Sb(g.Mb(a.g,function(b){return b}));
g.rb(a);a.length?g.ft("yt-remote-online-screen-ids",a.join(","),60):G5("yt-remote-online-screen-ids")},w7=function(a){j7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};Iqa(this)},y7=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Id();if(k=(c?F5(k,c):null)||F5(k,b)){k.uuid=b;var l=x7(a,k);s7(a.i,l,function(m){e(m?l:null)})}else c?Jqa(a,c,(0,g.x)(function(m){var n=x7(this,new x5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));s7(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},z7=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Jqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={tb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Fq($6(a.A,"/pairing/get_lounge_token_batch"),e)},A7=function(a){a.g=a.l.Id();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+C5(a.g))},Iqa=function(a){B7(a);
a.l=new n7(a.A);a.l.subscribe("screenChange",(0,g.x)(a.DD,a));A7(a);a.o=A5(g.gt("yt-remote-automatic-screen-cache")||[]);B7(a);a.info("Initializing automatic screens: "+C5(a.o));a.i=new r7(a.A,(0,g.x)(a.Id,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.N("onlineScreenChange")},a))},x7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=F5(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.ft("yt-remote-automatic-screen-cache",(0,g.B)(a.o,z5)));B7(a);a.u[b.uuid]=b.id;g.ft("yt-remote-device-id-map",a.u,31536E3);return b},B7=function(a){a.u=g.gt("yt-remote-device-id-map")||{}},C7=function(a,b,c){g.P.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},D7=function(a,b){f7(a.P,b)},F7=function(a,b){C7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.x)(this.mN,this);this.u=(0,g.x)(this.OL,this);this.o=g.Ip((0,g.x)(function(){E7(this,null)},this),12E4)},Kqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Kg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ja,(0,g.x)(function(){D7(this,"Failed to send message: getMdxSessionStatus.")},a)):D7(a,"Sending yt message without session: "+g.Kg(b))},E7=function(a,b){g.Kp(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.wn,a),d=(0,g.x)(a.Ld,a);a.Nv(b,c,d,5)}}else a.Ld(Error("Waiting for session status timed out."))},G7=function(a,b,c){C7.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.C=g.Ja;this.A=NaN;this.I=(0,g.x)(this.pN,this);this.g=g.Ja},H7=function(a){a.g=a.F.fB(a.H,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ja;
this.wn(b)},a),(0,g.x)(function(b){this.g=g.Ja;
this.Ld(b)},a))},I7=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}R5()&&(b.env_useStageMdx=1);return g.ah(b)},J7=function(a,b){C7.call(this,a,b,"ManualSession");
this.g=g.Ip((0,g.x)(this.li,this,null),150)},K7=function(a,b,c,d){g.P.call(this);
this.i=a;this.C=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.uK,this)},L7=function(a,b){return b?g.Ya(a.l,function(c){return y5(b,c.label)},a):null},M7=function(a){f7("Controller",a)},b7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},N7=function(a){return a.u||!!a.l.length||!!a.g},O7=function(a,b,c){b!=a.g&&(g.qf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.Uy,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.li(null)):a.N("yt-remote-cast2-session-change",null))},P7=function(a){var b=a.i.eB(),c=a.g&&a.g.i;
a=(0,g.B)(b,function(d){c&&y5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=L7(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Oqa=function(a,b,c,d,e,f,k){Lqa()?Mqa(b,e,f,k)&&(R7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?S7(a,c):(window.__onGCastApiAvailable=function(l,m){l?S7(a,c):(T7("Failed to load cast API: "+m),U7(!1),R7(!1),G5("yt-remote-cast-available"),G5("yt-remote-cast-receiver"),V7(),c(!1))},d?g.Vp("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?vqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?W5():(X5(),V5(Nqa.map(tqa))))):Q7("Cannot initialize because not running Chrome")},V7=function(){Q7("dispose");
var a=W7();a&&a.dispose();g.Ia("yt.mdx.remote.cloudview.instance_",null,void 0);X7(!1);g.Qp(Y7);Y7.length=0},Z7=function(){return!!g.gt("yt-remote-cast-installed")},$7=function(){var a=g.gt("yt-remote-cast-receiver");
return a?a.friendlyName:null},a8=function(){Q7("clearCurrentReceiver");
G5("yt-remote-cast-receiver")},b8=function(){return Z7()?W7()?W7().getCastSession():(T7("getCastSelector: Cast is not initialized."),null):(T7("getCastSelector: Cast API is not installed!"),null)},d8=function(){Z7()?W7()?c8()?(Q7("Requesting cast selector."),W7().requestSession()):(Q7("Wait for cast API to be ready to request the session."),Y7.push(g.Pp("yt-remote-cast2-api-ready",d8))):T7("requestCastSelector: Cast is not initialized."):T7("requestCastSelector: Cast API is not installed!")},e8=function(a,
b){c8()?W7().setConnectedScreenStatus(a,b):T7("setConnectedScreenStatus called before ready.")},Lqa=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Ow||a},Pqa=function(a,b){W7().init(a,b)},Mqa=function(a,b,c,d){var e=!1;
W7()||(a=new K7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.ft("yt-remote-cast-available",f);v5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){Q7("onReceiverSelected: "+f.friendlyName);
g.ft("yt-remote-cast-receiver",f);v5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){Q7("onReceiverResumed: "+f.friendlyName);
g.ft("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){Q7("onSessionChange: "+B5(f));
f||G5("yt-remote-cast-receiver");v5("yt-remote-cast2-session-change",f)}),g.Ia("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
Q7("cloudview.createSingleton_: "+e);return e},W7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},S7=function(a,b){U7(!0);
R7(!1);Pqa(a,function(c){c?(X7(!0),g.Sp("yt-remote-cast2-api-ready")):(T7("Failed to initialize cast API."),U7(!1),G5("yt-remote-cast-available"),G5("yt-remote-cast-receiver"),V7());b(c)})},Q7=function(a){f7("cloudview",a)},T7=function(a){f7("cloudview",a)},U7=function(a){Q7("setCastInstalled_ "+a);
g.ft("yt-remote-cast-installed",a)},c8=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},X7=function(a){Q7("setApiReady_ "+a);
g.Ia("yt.mdx.remote.cloudview.apiReady_",a,void 0)},R7=function(a){g.Ia("yt.mdx.remote.cloudview.initializing_",a,void 0)},f8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.C=0;this.g=null;this.hasNext=this.Je=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},g8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Je=!1;a.hasNext=!1;a.C=0;a.A=(0,g.H)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},h8=function(a){return 1==a.playerState?((0,g.H)()-a.A)/1E3:0},i8=function(a,b){a.C=b;
a.A=(0,g.H)()},j8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.A)/1E3+a.C;
case -1E3:return 0}return a.C},k8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&g8(a)},l8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.g);b.hasPrevious=a.Je;b.hasNext=a.hasNext;b.playerTime=a.C;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},o8=function(a,b){g.P.call(this);
this.g=0;this.o=a;this.A=[];this.u=new u5;this.l=this.i=null;this.F=(0,g.x)(this.rI,this);this.C=(0,g.x)(this.Ak,this);this.D=(0,g.x)(this.qI,this);this.H=(0,g.x)(this.FI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ys,this),m8(this))):c=3;0!=c&&(b?this.Ys(c):g.Ip((0,g.x)(function(){this.Ys(c)},this),0));
var d=b8();d&&n8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},p8=function(a){return new f8(a.o.getPlayerContextData())},m8=function(a){(0,g.z)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Sa(this.rK,b),this))},a)},q8=function(a){(0,g.z)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},r8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},t8=function(a,b,c){var d=p8(a);
i8(d,c);-1E3!=d.playerState&&(d.playerState=b);s8(a,d)},u8=function(a,b,c){a.o.sendMessage(b,c)},s8=function(a,b){q8(a);
a.o.setPlayerContextData(l8(b));m8(a)},n8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.C),a.Ak(null));
a.l=b;a.l&&(f7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.C),a.l.media.length&&a.Ak(a.l.media[0]))},v8=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=p8(a);b.contentId!=d.videoId&&f7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;i8(d,a.i.getEstimatedTime());s8(a,d)}else f7("CP","No cast media video. Ignoring state update.")},w8=function(a,b,c){return(0,g.x)(function(d){this.Hb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Hb("Retrying "+b+" using MDx browser channel."),u8(this,b,c))},a)},x8=function(a,b,c){g.P.call(this);
this.u=NaN;this.I=!1;this.D=this.C=this.F=this.H=NaN;this.P=[];this.o=this.A=this.l=this.Oa=this.g=null;this.O=a;this.P.push(g.Nr(window,"beforeunload",(0,g.x)(this.oD,this)));this.i=[];this.Oa=new f8;this.M=b.id;this.g=Qqa(this,c);this.g.subscribe("handlerOpened",this.vI,this);this.g.subscribe("handlerClosed",this.sI,this);this.g.subscribe("handlerError",this.tI,this);this.g.subscribe("handlerMessage",this.uI,this);Aqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Oa.videoId;
g.ht()&&g.ft("yt-remote-session-video-id",d)},this)},y8=function(a){f7("conn",a)},Qqa=function(a,b){return new W6($6(a.O,"/bc"),b)},z8=function(a,b){a.N("proxyStateChange",b)},Rqa=function(a){a.u=g.Ip((0,g.x)(function(){y8("Connecting timeout");
this.Nh(1)},a),2E4)},A8=function(a){g.Kp(a.u);
a.u=NaN},B8=function(a){g.Kp(a.H);
a.H=NaN},Sqa=function(a){C8(a);
a.F=g.Ip((0,g.x)(function(){D8(this,"getNowPlaying")},a),2E4)},C8=function(a){g.Kp(a.F);
a.F=NaN},F8=function(a,b){b&&(A8(a),B8(a));
b==(Y6(a.g)&&isNaN(a.u))?b&&(z8(a,1),D8(a,"getSubtitlesTrack")):b?(a.Kv()&&a.Oa.reset(),z8(a,1),D8(a,"getNowPlaying"),E8(a)):a.Nh(1)},Tqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Oa.videoId&&(g.Yb(b.params)?a.Oa.g=null:a.Oa.g=b.params,a.N("remotePlayerChange"))},G8=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Oa.listId=b.params.listId||a.Oa.listId;k8(a.Oa,c,d);a.N("remoteQueueChange")},Uqa=function(a,b){b.params=b.params||{};
G8(a,b);H8(a,b);a.N("autoplayDismissed")},H8=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
i8(a.Oa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Oa.playerState&&(c=-1E3);a.Oa.playerState=c;c=Number(b.params.loadedTime);a.Oa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Oa.D=isNaN(c)?0:c;c=a.Oa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Oa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Oa.playerState?Sqa(a):C8(a);a.N("remotePlayerChange")},Vqa=function(a,b){if(-1E3!=
a.Oa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Oa.playerState=c;c=parseInt(b.params.currentTime,10);i8(a.Oa,isNaN(c)?0:c);a.N("remotePlayerChange")}},Wqa=function(a,b){var c="true"==b.params.muted;
a.Oa.volume=parseInt(b.params.volume,10);a.Oa.muted=c;a.N("remotePlayerChange")},Xqa=function(a,b){a.A=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},Yqa=function(a,b){var c="true"==b.params.hasNext;
a.Oa.Je="true"==b.params.hasPrevious;a.Oa.hasNext=c;a.N("previousNextChange")},E8=function(a){g.Kp(a.D);
a.D=g.Ip((0,g.x)(a.Nh,a,1),864E5)},D8=function(a,b,c){c?y8("Sending: action="+b+", params="+g.Kg(c)):y8("Sending: action="+b);
a.g.sendMessage(b,c)},I8=function(a){j7.call(this,"ScreenServiceProxy");
this.Vc=a;this.i=[];this.i.push(this.Vc.$_s("screenChange",(0,g.x)(this.kN,this)));this.i.push(this.Vc.$_s("onlineScreenChange",(0,g.x)(this.WJ,this)))},cra=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Ap("MDX_CONFIG")||b;pqa();L5();J8||(J8=new Z6(b?b.loungeApiHost:void 0),R5()&&(J8.g="/api/loungedev"));K8||(K8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ia("yt.mdx.remote.deferredProxies_",K8,void 0));Zqa();var c=L8();if(!c){var d=new w7(J8);g.Ia("yt.mdx.remote.screenService_",d,void 0);c=L8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Oqa(a,d,function(m){m?M8()&&e8(M8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){v5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ia("yt.mdx.remote.initialized_",!0,void 0),N8("Initializing: "+g.Kg(b)),O8.push(g.Pp("yt-remote-cast2-availability-change",function(){v5("yt-remote-receiver-availability-change")})),O8.push(g.Pp("yt-remote-cast2-receiver-selected",function(){P8(null);
v5("yt-remote-auto-connect","cast-selector-receiver")})),O8.push(g.Pp("yt-remote-cast2-receiver-resumed",function(){v5("yt-remote-receiver-resumed","cast-selector-receiver")})),O8.push(g.Pp("yt-remote-cast2-session-change",$qa)),O8.push(g.Pp("yt-remote-connection-change",function(m){m?e8(M8(),"YouTube TV"):Q8()||(e8(null,null),a8())})),a=R8(),b.isAuto&&(a.id+="#dial"),g.wq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),N8(" -- with channel params: "+
g.Kg(a)),ara(a),c.start(),M8()||bra())},dra=function(){var a=S8();
Z7()&&g.gt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},S8=function(){var a=L8().Vc.$_gos();
var b=T8();b&&U8()&&(E5(a,b)||a.push(b));return oqa(a)},V8=function(){var a=era();
!a&&Z7()&&$7()&&(a={key:"cast-selector-receiver",name:$7()});return a},era=function(){var a=S8(),b=T8();
b||(b=Q8());return g.Ya(a,function(c){return b&&y5(b,c.key)?!0:!1})},T8=function(){var a=M8();
if(!a)return null;var b=L8().Id();return F5(b,a)},$qa=function(a){N8("remote.onCastSessionChange_: "+B5(a));
if(a){var b=T8();b&&b.id==a.id?e8(b.id,"YouTube TV"):(b&&W8(),X8(a,1))}else U8()&&W8()},W8=function(){c8()?W7().stopSession():T7("stopSession called before API ready.");
var a=U8();a&&(a.disconnect(1),Y8(null))},Z8=function(){var a=U8();
return!!a&&3!=a.getProxyState()},N8=function(a){f7("remote",a)},L8=function(){if(!$8){var a=g.w("yt.mdx.remote.screenService_");
$8=a?new I8(a):null}return $8},M8=function(){return g.w("yt.mdx.remote.currentScreenId_")},a9=function(a){g.Ia("yt.mdx.remote.currentScreenId_",a,void 0)},b9=function(){return g.w("yt.mdx.remote.connectData_")},P8=function(a){g.Ia("yt.mdx.remote.connectData_",a,void 0)},U8=function(){return g.w("yt.mdx.remote.connection_")},Y8=function(a){var b=U8();
P8(null);a||a9("");g.Ia("yt.mdx.remote.connection_",a,void 0);K8&&((0,g.z)(K8,function(c){c(a)}),K8.length=0);
b&&!a?v5("yt-remote-connection-change",!1):!b&&a&&v5("yt-remote-connection-change",!0)},Q8=function(){var a=g.ht();
if(!a)return null;var b=L8().Id();return F5(b,a)},X8=function(a,b){T8()&&T8();
if(c9)d9=a;else{a9(a.id);var c=new x8(J8,a,R8());c.connect(b,b9());c.subscribe("beforeDisconnect",function(d){v5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){U8()&&Y8(null)});
Y8(c)}},bra=function(){var a=Q8();
a?(N8("Resume connection to: "+B5(a)),X8(a,0)):(P5(),a8(),N8("Skipping connecting because no session screen found."))},Zqa=function(){var a=R8();
if(g.Yb(a)){a=K5();var b=g.gt("yt-remote-session-name")||"",c=g.gt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ia("yt.mdx.remote.channelParams_",a,void 0)}},R8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},ara=function(a){a?(g.ft("yt-remote-session-app",a.app),g.ft("yt-remote-session-name",a.name)):(G5("yt-remote-session-app"),G5("yt-remote-session-name"));
g.Ia("yt.mdx.remote.channelParams_",a,void 0)},e9=function(a,b,c){g.D.call(this);
this.u=a;this.i=b;this.l=new g.vs(this);g.G(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.qJ);this.l.K(b,"captionschanged",this.pI);this.l.K(b,"captionssettingschanged",this.tA);this.l.K(b,"videoplayerreset",this.xn);this.l.K(b,"mdxautoplaycancel",this.qC);this.O=this.l.K(b,"onVolumeChange",this.Fy);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Qy,this);c.subscribe("remotePlayerChange",this.Ck,this);c.subscribe("remoteQueueChange",this.xn,this);c.subscribe("autoplayUpNext",this.ty,
this);c.subscribe("previousNextChange",this.Ny,this);c.subscribe("nowAutoplaying",this.Jy,this);c.subscribe("autoplayDismissed",this.ry,this);this.suggestion=null;this.F=new g.iC(64);this.o=new g.M(this.rA,500,this);g.G(this,this.o);this.A=new g.M(this.sA,1E3,this);g.G(this,this.A);this.I=new Y5(this.RM,0,this);g.G(this,this.I);this.C={};this.P=new g.M(this.RA,1E3,this);g.G(this,this.P);this.H=new g.Al(this.MF,1E3,this);g.G(this,this.H);this.M=g.Ja;this.tA();this.xn();this.Ck()},f9=function(a,b){a.u.Kc(b,
a.i.getVideoData().lengthSeconds)},h9=function(a){f9(a,0);
a.o.stop();g9(a,new g.iC(64))},j9=function(a,b){if(i9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.fc(c,b));a.g.gA(a.i.getVideoData(1).videoId,c);a.C=p8(a.g).g}},k9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Sa;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Df,q5(c));g9(a,new g.iC(1))},l9=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{GQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},i9=function(a){return p8(a.g).videoId==a.i.getVideoData(1).videoId},g9=function(a,b){a.A.stop();
var c=a.F;if(!g.oC(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.$J(a.i,d);a.F=b;m9(a.u,c,b)}},n9=function(){g.W.call(this,{B:"div",
G:"ytp-mdx-popup-dialog",L:{role:"dialog"},J:[{B:"div",G:"ytp-mdx-popup-dialog-inner-content",J:[{B:"div",G:"ytp-mdx-popup-title",T:"You're signed out"},{B:"div",G:"ytp-mdx-popup-description",T:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{B:"div",G:"ytp-mdx-privacy-popup-buttons",J:[{B:"button",V:["ytp-button","ytp-mdx-privacy-popup-cancel"],T:"Cancel"},{B:"button",V:["ytp-button","ytp-mdx-privacy-popup-confirm"],
T:"Confirm"}]}]}]});this.l=new g.TP(this,250);g.G(this,this.l);this.C=this.i["ytp-mdx-privacy-popup-cancel"];this.K(this.C,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.K(this.u,"click",this.A)},p9=function(a){g.W.call(this,{B:"div",
G:"ytp-remote",J:[{B:"div",G:"ytp-remote-display-status",J:[{B:"div",G:"ytp-remote-display-status-icon",J:[g.iP()]},{B:"div",G:"ytp-remote-display-status-text",T:"{{statustext}}"}]}]});this.l=new g.TP(this,250);g.G(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);o9(this,g.WJ(a))},o9=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.hN("Error on $RECEIVER_NAME",c):g.pC(b)||g.U(b,4)?g.hN("Playing on $RECEIVER_NAME",c):g.hN("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},q9=function(a,b){g.DT.call(this,"Play on",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},r9=function(a){g.yK.call(this,a);
this.i={key:D5(),name:"This computer"};this.u=null;this.o=[];this.C=this.g=null;this.A=[this.i];this.l=this.i;this.kk=new g.iC(64);this.H=0;this.Km=-1;if(!g.Oy(g.X(this.player))){a=this.player;var b=g.cD(a);b&&(b=b.dn())&&(b=new q9(a,b),g.G(this,b));b=new p9(a);g.G(this,b);g.kK(a,b.element,4);this.F=new n9;g.G(this,this.F);g.kK(a,this.F.element,4);this.D=!!Q8()}},m9=function(a,b,c){a.kk=c;
a.player.N("presentingplayerstatechange",new g.tD(c,b))},s9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)W8();
else{var c;if(c=g.Q(g.X(a.player).experiments,"mdx_enable_privacy_disclosure"))c=g.Ap("PLAYER_CONFIG"),c=!(c&&c.args&&void 0!==c.args.authuser||g.Ap("SESSION_INDEX")||g.Ap("LOGGED_IN"));c&&!a.D&&(a.player.pauseVideo(),a.F.l.show(),U8()||(c9=!0));a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,
playerParams:c.playerParams,clickTrackingParams:c.Df,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=q5(c))&&(d.locationInfo=c);c=d}else c=null;N8("Connecting to: "+g.Kg(b));"cast-selector-receiver"==b.key?(P8(c||null),c8()?W7().setLaunchParams(c||null):T7("setLaunchParams called before ready.")):!c&&Z8()&&M8()==b.key?v5("yt-remote-connection-change",!0):(W8(),P8(c||null),c=L8().Id(),(c=F5(c,b.key))&&X8(c,1))}},eqa=/^https?$/i,fra=["POST",
"PUT"];g.y(o5,g.Sf);g.h=o5.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.l="";this.u=0;this.aa=b;this.O=!1;this.i=!0;this.g=this.M?g5(this.M):g5(g.EY);this.P=this.M?this.M.getOptions():g.EY.getOptions();this.g.onreadystatechange=(0,g.x)(this.Xv,this);try{d5(h5(this,"Opening Xhr")),this.W=!0,this.g.open(b,String(a),!0),this.W=!1}catch(f){d5(h5(this,"Error opening Xhr: "+f.message));l5(this,f);return}a=c||
"";var e=this.headers.clone();d&&bqa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.Hd(),cqa);c=g.v.FormData&&a instanceof g.v.FormData;!g.ab(fra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Z&&(this.g.responseType=this.Z);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{i5(this),0<this.A&&(this.I=dqa(this.g),d5(h5(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.x)(this.Yv,this)):this.F=g.Gg(this.Yv,this.A,this)),d5(h5(this,"Sending request")),this.C=!0,this.g.send(a),this.C=!1}catch(f){d5(h5(this,"Send error: "+f.message)),l5(this,f)}};
g.h.Yv=function(){"undefined"!=typeof g.hY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,h5(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(h5(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),k5(this))};
g.h.U=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),k5(this,!0));o5.Xa.U.call(this)};
g.h.Xv=function(){this.ea()||(this.W||this.C||this.o?n5(this):this.tK())};
g.h.tK=function(){n5(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<m5(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.Fa(this.l)?this.l:String(this.l)};
var m6={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},l6={"'":"\\'"},gra={};g.h=u5.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.ab(this.g,a)||g.ab(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Oma)(b,a);0<=c?(g.cb(b,c),b=!0):b=!1;return b||g.db(this.i,a)};
g.h.zc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var mqa={IN:"atp",UP:"ska",JP:"que",iP:"mus",TP:"sus",zO:"dsp",QP:"seq"};w5.prototype.hg=function(){var a=new w5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var Q5,J5="",uqa=S5("loadCastFramework")||S5("loadCastApplicationFramework"),Nqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.y(Y5,g.D);g.h=Y5.prototype;g.h.kD=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.H)()+this.Wc:this.za=g.Gg(this.u,this.Wc)};
g.h.stop=function(){this.za&&(g.v.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.U=function(){this.stop();Y5.Xa.U.call(this)};
g.h.lD=function(){this.l?(this.za=g.Gg(this.u,this.l-(0,g.H)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};Z5.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
Z5.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=$5.prototype;g.h.bh=null;g.h.xe=!1;g.h.Wi=null;g.h.Vs=null;g.h.Fi=null;g.h.Wh=null;g.h.Yf=null;g.h.Fg=null;g.h.uh=null;g.h.tc=null;g.h.il=0;g.h.Be=null;g.h.lo=null;g.h.qg=null;g.h.Rj=-1;g.h.Tz=!0;g.h.Qg=!1;g.h.Qp=0;g.h.Hn=null;var g6={},e6={};g.h=$5.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.cM=function(a){a=a.target;var b=this.Hn;b&&3==m5(a)?b.Nj():this.aB(a)};
g.h.aB=function(a){try{if(a==this.tc)a:{var b=m5(this.tc),c=this.tc.u,d=this.tc.getStatus();if(g.Md&&!g.pd(10)||g.Od&&!g.od("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ch&&!p5(this.tc))break a;this.Qg||4!=b||7==c||(8==c||0>=d?this.g.te(3):this.g.te(2));q6(this);var e=this.tc.getStatus();this.Rj=e;var f=p5(this.tc);(this.xe=200==e)?(4==b&&i6(this),this.u?(k6(this,b,f),g.Ch&&this.xe&&3==b&&(this.ba.ca(this.i,"tick",this.VL),this.i.start())):h6(this,f),this.xe&&!this.Qg&&(4==b?this.g.un(this):(this.xe=
!1,d6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.qg=3,f6(13)):(this.qg=0,f6(14)),i6(this),j6(this))}}catch(k){this.tc&&p5(this.tc)}finally{}};
g.h.VL=function(){var a=m5(this.tc),b=p5(this.tc);this.il<b.length&&(q6(this),k6(this,a,b),this.xe&&4!=a&&d6(this))};
g.h.tL=function(a){p6((0,g.x)(this.sL,this,a),0)};
g.h.sL=function(a){this.Qg||(q6(this),h6(this,a),d6(this))};
g.h.Xy=function(a){p6((0,g.x)(this.rL,this,a),0)};
g.h.rL=function(a){this.Qg||(i6(this),this.xe=a,this.g.un(this),this.g.te(4))};
g.h.cancel=function(){this.Qg=!0;i6(this)};
g.h.DL=function(){this.Wi=null;var a=(0,g.H)();0<=a-this.Vs?(2!=this.Wh&&this.g.te(3),i6(this),this.qg=2,f6(18),j6(this)):o6(this,this.Vs-a)};
g.h.getLastError=function(){return this.qg};g.h=u6.prototype;g.h.Op=null;g.h.Cd=null;g.h.In=!1;g.h.Wv=null;g.h.dm=null;g.h.Cq=null;g.h.Pp=null;g.h.ce=null;g.h.Af=-1;g.h.Qj=null;g.h.ij=null;g.h.connect=function(a){this.Pp=a;a=v6(this.g,null,this.Pp);f6(3);this.Wv=(0,g.H)();var b=this.g.D;null!=b?(this.Qj=b[0],(this.ij=b[1])?(this.ce=1,w6(this)):(this.ce=2,y6(this))):(f5(a,"MODE","init"),this.Cd=new $5(this,void 0,void 0,void 0),this.Cd.bh=this.Op,c6(this.Cd,a,!1,null,!0),this.ce=0)};
g.h.rC=function(a){if(a)this.ce=2,y6(this);else{f6(4);var b=this.g;b.Ie=b.gg.Af;S6(b,9)}a&&this.te(2)};
g.h.lp=function(a){return this.g.lp(a)};
g.h.abort=function(){this.Cd&&(this.Cd.cancel(),this.Cd=null);this.Af=-1};
g.h.Vv=function(){return!1};
g.h.Ry=function(a,b){this.Af=a.Rj;if(0==this.ce)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ie=this.Af;S6(c,2);return}this.Qj=c[0];this.ij=c[1]}else c=this.g,c.Ie=this.Af,S6(c,2);else if(2==this.ce)if(this.In)f6(7),this.Cq=(0,g.H)();else if("11111"==b){if(f6(6),this.In=!0,this.dm=(0,g.H)(),c=this.dm-this.Wv,!g.Md||g.pd(10)||500>c)this.Af=200,this.Cd.cancel(),f6(12),x6(this.g,this,!0)}else f6(8),this.dm=this.Cq=(0,g.H)(),this.In=!1};
g.h.un=function(){this.Af=this.Cd.Rj;if(this.Cd.xe)0==this.ce?this.ij?(this.ce=1,w6(this)):(this.ce=2,y6(this)):2==this.ce&&((!g.Md||g.pd(10)?!this.In:200>this.Cq-this.dm)?(f6(11),x6(this.g,this,!1)):(f6(12),x6(this.g,this,!0)));else{0==this.ce?f6(9):2==this.ce&&f6(10);var a=this.g;this.Cd.getLastError();a.Ie=this.Af;S6(a,2)}};
g.h.Qk=function(){return this.g.Qk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.te=function(a){this.g.te(a)};g.h=z6.prototype;g.h.vj=null;g.h.yd=null;g.h.Sb=null;g.h.Np=null;g.h.gm=null;g.h.nu=null;g.h.rm=null;g.h.xk=0;g.h.JH=0;g.h.Tc=null;g.h.mg=null;g.h.nf=null;g.h.Vg=null;g.h.gg=null;g.h.jo=null;g.h.ji=-1;g.h.Ew=-1;g.h.Ie=-1;g.h.Qh=0;g.h.Jh=0;g.h.Rg=8;var T6=new g.Sf;g.y(A6,g.sf);g.y(B6,g.sf);g.y(C6,g.sf);g.h=z6.prototype;g.h.connect=function(a,b,c,d,e){f6(0);this.Np=b;this.vj=c||{};d&&g.Ea(e)&&(this.vj.OSID=d,this.vj.OAID=e);this.A?(p6((0,g.x)(this.Hu,this,a),100),I6(this)):this.Hu(a)};
g.h.Hu=function(a){this.gg=new u6(this);this.gg.Op=null;this.gg.i=this.u;this.gg.connect(a)};
g.h.Vv=function(){return 0==this.g};
g.h.Wy=function(a){this.mg=null;N6(this,a)};
g.h.Vy=function(){this.nf=null;this.Sb=new $5(this,this.l,"rpc",this.C);this.Sb.bh=null;this.Sb.Qp=0;var a=this.nu.clone();g.Vm(a,"RID","rpc");g.Vm(a,"SID",this.l);g.Vm(a,"CI",this.jo?"0":"1");g.Vm(a,"AID",this.ji);E6(this,a);if(!g.Md||g.pd(10))g.Vm(a,"TYPE","xmlhttp"),c6(this.Sb,a,!0,this.rm,!1);else{g.Vm(a,"TYPE","html");var b=this.Sb,c=!!this.rm;b.Wh=3;b.Yf=e5(a.clone());n6(b,c)}};
g.h.Ry=function(a,b){if(0!=this.g&&(this.Sb==a||this.yd==a))if(this.Ie=a.Rj,this.yd==a&&3==this.g)if(7<this.Rg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ma(c)&&3==c.length)if(0==c[0])a:{if(!this.nf){if(this.Sb)if(this.Sb.Fi+3E3<this.yd.Fi)J6(this),this.Sb.cancel(),this.Sb=null;else break a;Q6(this);f6(19)}}else this.Ew=c[1],0<this.Ew-this.ji&&37500>c[2]&&this.jo&&0==this.Jh&&!this.Vg&&(this.Vg=p6((0,g.x)(this.lI,this),6E3));else S6(this,11)}else b!=gra.eO.g&&S6(this,11);else if(this.Sb==a&&
J6(this),!g.xb(b)){c=this.u.parse(b);g.Ma(c);for(var d=0;d<c.length;d++){var e=c[d];this.ji=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.rm=e[2],e=e[3],null!=e?this.Rg=e:this.Rg=6,this.g=3,this.Tc&&this.Tc.Bu(),this.nu=v6(this,this.Qk()?this.rm:null,this.Np),O6(this)):"stop"==e[0]&&S6(this,7):3==this.g&&("stop"==e[0]?S6(this,7):"noop"!=e[0]&&this.Tc&&this.Tc.Au(e),this.Jh=0)}}};
g.h.lI=function(){null!=this.Vg&&(this.Vg=null,this.Sb.cancel(),this.Sb=null,Q6(this),f6(20))};
g.h.un=function(a){if(this.Sb==a){J6(this);this.Sb=null;var b=2}else if(this.yd==a)this.yd=null,b=1;else return;this.Ie=a.Rj;if(0!=this.g)if(a.xe)1==b?(b=(0,g.H)()-a.Fi,T6.dispatchEvent(new B6(T6,a.uh?a.uh.length:0,b,this.Qh)),H6(this),this.o.length=0):O6(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ie)){if(d=1==b)this.yd||this.mg||1==this.g||2<=this.Qh?d=!1:(this.mg=p6((0,g.x)(this.Wy,this,a),P6(this,this.Qh)),this.Qh++,d=!0);d=!(d||2==b&&Q6(this))}if(d)switch(c){case 1:S6(this,
5);break;case 4:S6(this,10);break;case 3:S6(this,6);break;case 7:S6(this,12);break;default:S6(this,2)}}};
g.h.KC=function(a){if(!g.ab(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.HM=function(a){a?f6(2):(f6(1),R6(this,8))};
g.h.lp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new o5;a.R=!1;return a};
g.h.isActive=function(){return!!this.Tc&&this.Tc.isActive(this)};
g.h.te=function(a){T6.dispatchEvent(new C6(T6,a))};
g.h.Qk=function(){return!(!g.Md||g.pd(10))};
g.h=U6.prototype;g.h.Bu=function(){};
g.h.Au=function(){};
g.h.zu=function(){};
g.h.Yo=function(){};
g.h.xv=function(){return{}};
g.h.isActive=function(){return!0};g.y(V6,g.D);g.h=V6.prototype;g.h.lL=function(){this.Wc=Math.min(3E5,2*this.Wc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Wc+15E3*Math.random();g.bo(this.g,a);this.i=(0,g.H)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Wc=5E3};g.y(W6,U6);g.h=W6.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Kf=function(a){return this.l.eh(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.fb||(this.fb=!0,g.qf(this.l),X6(this),g.qf(this.i),this.i=null)};
g.h.ea=function(){return this.fb};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new z6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Tc=null);d.Tc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.ji):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.C.push(c):Y6(this)&&K6(this.g,c)};
g.h.Bu=function(){this.i.reset();this.u=null;this.o=0;if(this.C.length){var a=this.C;this.C=[];for(var b=0,c=a.length;b<c;++b)K6(this.g,a[b])}this.N("handlerOpened")};
g.h.zu=function(a){var b=2==a&&401==this.g.Ie;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.Yo=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.C.push(d)}};
g.h.xv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.fc(a,this.u);return a};
g.h.Au=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),G6(this.g)):this.N("handlerMessage",new yqa(a[0],a[1]))};
g.h.lM=function(){this.i.isActive();var a=this.g,b=0;a.Sb&&b++;a.yd&&b++;0==b&&this.connect(this.u,this.o)};Z6.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Z6.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
Z6.prototype.u=function(a){a(Error("request timed out"))};var Eqa=(0,g.H)(),d7=null,h7=Array(50),g7=-1,i7=!1;g.y(j7,g.P);j7.prototype.Id=function(){return this.g};
j7.prototype.contains=function(a){return!!E5(this.g,a)};
j7.prototype.get=function(a){return a?F5(this.g,a):null};
j7.prototype.info=function(a){f7(this.C,a)};g.t(l7,g.P);g.h=l7.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.dB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.Kp(this.za),this.za=NaN)};
g.h.U=function(){this.stop();g.P.prototype.U.call(this)};
g.h.dB=function(){this.za=NaN;this.g=g.Fq($6(this.A,"/pairing/get_screen"),{method:"POST",tb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.iN,this),onError:(0,g.x)(this.hN,this),ie:(0,g.x)(this.jN,this)})};
g.h.iN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new x5(c))};
g.h.hN=function(a){this.g=null;a.status&&404==a.status?this.i>=t9.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=t9[this.i],this.za=g.Ip((0,g.x)(this.dB,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.jN=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};
var t9=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.y(n7,j7);g.h=n7.prototype;g.h.start=function(){m7(this)&&this.N("screenChange");!g.gt("yt-remote-lounge-token-expiration")&&o7(this);g.Kp(this.i);this.i=g.Ip((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){m7(this);k7(this,a);p7(this,!1);this.N("screenChange");b(a);a.token||o7(this)};
g.h.remove=function(a,b){var c=m7(this);Gqa(this,a)&&(p7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.co=function(a,b,c,d){var e=m7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,p7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.U=function(){g.Kp(this.i);n7.Xa.U.call(this)};
g.h.vD=function(a){m7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}p7(this,!b);b&&f7(this.C,"Missed "+b+" lounge tokens.")};
g.h.uD=function(a){f7(this.C,"Requesting lounge tokens failed: "+a)};g.t(r7,g.P);g.h=r7.prototype;g.h.start=function(){var a=parseInt(g.gt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.H)()-144E5<a?0:a)?u7(this):(this.o=(0,g.H)()+3E5,g.ft("yt-remote-fast-check-period",this.o),this.Wr())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){q7("Updating availability on schedule.");var a=this.A(),b=g.Mb(this.g,function(c,d){return c&&!!F5(a,d)},this);
t7(this,b)};
g.h.U=function(){g.Kp(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.P.prototype.U.call(this)};
g.h.Wr=function(){g.Kp(this.l);this.l=NaN;this.i&&this.i.abort();var a=v7(this);if(r5(a)){var b=$6(this.u,"/pairing/get_screen_availability");this.i=a7(this.u,b,{lounge_token:g.Sb(a).join(",")},(0,g.x)(this.PK,this,a),(0,g.x)(this.OK,this))}else t7(this,{}),u7(this)};
g.h.PK=function(a,b){this.i=null;var c=g.Sb(v7(this));if(g.sb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;t7(this,d);u7(this)}else this.Hb("Changing Screen set during request."),this.Wr()};
g.h.OK=function(a){this.Hb("Screen availability failed: "+a);this.i=null;u7(this)};
g.h.Hb=function(a){f7("OnlineScreenService",a)};g.y(w7,j7);g.h=w7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.co=function(a,b,c,d){this.l.contains(a)?this.l.co(a,b,c,d):(a="Updating name of unknown screen: "+a.name,f7(this.C,a),d(Error(a)))};
g.h.Id=function(a){return a?this.g:g.gb(this.g,(0,g.Yd)(this.o,function(b){return!this.contains(b)},this))};
g.h.eB=function(){return(0,g.Yd)(this.Id(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.fB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new l7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.qf(f);d(x7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.qf(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.lN=function(a,b,c,d){g.Fq($6(this.A,"/pairing/get_screen"),{method:"POST",tb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new x5(f.screen||{});if(!k.name||z7(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);z7(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(x7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
ie:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.qf(this.l);g.qf(this.i);w7.Xa.U.call(this)};
g.h.DD=function(){A7(this);this.N("screenChange");this.i.update()};
w7.prototype.dispose=w7.prototype.dispose;g.y(C7,g.P);g.h=C7.prototype;g.h.wn=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Ld=function(a){this.ea()||(a&&D7(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){f7(this.P,a)};
g.h.hB=function(){return null};
g.h.os=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){D7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.os("");C7.Xa.U.call(this)};g.y(F7,C7);g.h=F7.prototype;g.h.ls=function(a){if(this.g){if(this.g==a)return;D7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Kqa(this)};
g.h.li=function(a){this.info("launchWithParams no-op for Cast: "+g.Kg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Ld()},this),(0,g.x)(function(){this.Ld(Error("Failed to stop receiver app."))},this)):this.Ld(Error("Stopping cast device witout session."))};
g.h.os=g.Ja;g.h.U=function(){this.info("disposeInternal");g.Kp(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;F7.Xa.U.call(this)};
g.h.OL=function(a,b){if(!this.ea())if(b){var c=t5(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Kg(c));switch(d){case "mdxSessionStatus":E7(this,c.screenId);break;default:D7(this,"Unknown youtube message: "+d)}}else D7(this,"Unable to parse message.")}else D7(this,"No data in message.")};
g.h.Nv=function(a,b,c,d){y7(this.F,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(D7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Ip((0,g.x)(this.Nv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.hB=function(){return this.g};
g.h.mN=function(a){this.ea()||a||(D7(this,"Cast session died."),this.Ld())};g.y(G7,C7);g.h=G7.prototype;g.h.ls=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.li=function(a){this.u=a;this.C()};
g.h.stop=function(){this.g();this.g=g.Ja;g.Kp(this.A);this.o?this.o.stop((0,g.x)(this.Ld,this,null),(0,g.x)(this.Ld,this,"Failed to stop DIAL device.")):this.Ld()};
g.h.U=function(){this.g();this.g=g.Ja;g.Kp(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;G7.Xa.U.call(this)};
g.h.pN=function(a){this.ea()||a||(D7(this,"DIAL session died."),this.g(),this.g=g.Ja,this.Ld())};
g.h.eq=function(a){this.H=D5();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,I7(this));a(b);H7(this)}else this.C=(0,g.x)(function(){g.Kp(this.A);this.C=g.Ja;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,I7(this));a(c);H7(this)},this),this.A=g.Ip((0,g.x)(function(){this.C()},this),100)};
g.h.ZD=function(a,b,c){y7(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.wn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.eq(b,c)},this),(0,g.x)(function(d){D7(this,"Failed to get DIAL screen: "+d);
this.eq(b,c)},this))};g.y(J7,C7);J7.prototype.stop=function(){this.Ld()};
J7.prototype.ls=g.Ja;J7.prototype.li=function(){g.Kp(this.g);this.g=NaN;var a=F5(this.F.Id(),this.i.label);a?this.wn(a):this.Ld(Error("No such screen"))};
J7.prototype.U=function(){g.Kp(this.g);this.g=NaN;J7.Xa.U.call(this)};g.y(K7,g.P);g.h=K7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.C);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.yK,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.Ty,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.MI,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ea()||
(chrome.cast.addReceiverActionListener(this.o),Bqa(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.gB,this)),this.l=P7(this),chrome.cast.setCustomReceivers(this.l,g.Ja,(0,g.x)(function(k){this.Hb("Failed to set initial custom receivers: "+g.Kg(k))},this)),this.N("yt-remote-cast2-availability-change",N7(this)),b(!0))},this),(0,g.x)(function(k){this.Hb("Failed to initialize API: "+g.Kg(k));
b(!1)},this))};
g.h.uM=function(a,b){M7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)M7("Unsetting old screen status: "+this.g.i.friendlyName),O7(this,null)}if(a&&b){if(!this.g){c=F5(this.i.Id(),a);if(!c){M7("setConnectedScreenStatus: Unknown screen.");return}var d=L7(this,c);d||(M7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ja,(0,g.x)(function(e){this.Hb("Failed to set initial custom receivers: "+g.Kg(e))},this)));
M7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);O7(this,new J7(this.i,d),!0)}this.g.os(b)}else M7("setConnectedScreenStatus: no screen.")};
g.h.vM=function(a){this.ea()?this.Hb("Setting connection data on disposed cast v2"):this.g?this.g.li(a):this.Hb("Setting connection data without a session")};
g.h.oN=function(){this.ea()?this.Hb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),O7(this,null)):M7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.Ty,this),(0,g.x)(this.UK,this))};
g.h.U=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.gB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.db(g.w("yt.mdx.remote.debug.handlers_")||[],b7);g.qf(this.g);K7.Xa.U.call(this)};
g.h.Hb=function(a){f7("Controller",a)};
g.h.Uy=function(a,b){this.g==a&&(b||O7(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.uK=function(a,b){if(!this.ea())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),M7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)M7("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{M7("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:O7(this,
new J7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:O7(this,new G7(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:O7(this,new F7(this.i,a));break;default:this.Hb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Hb("Stopping receiver w/o session: "+a.friendlyName)}else this.Hb("onReceiverAction_ called without receiver.")};
g.h.MI=function(a){if(this.ea())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Hb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Hb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return M7("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Hb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);O7(this,new G7(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.ZD,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.x)(b.eq,b))};
g.h.Ty=function(a){if(!this.ea()){M7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)M7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),O7(this,new F7(this.i,b),!0);else{this.Hb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=F5(this.i.Id(),c.label);d&&y5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(M7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.qf(this.g),this.g=new F7(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.Uy,this,this.g)),this.g.li(null));this.g.ls(a)}}};
g.h.nN=function(){return this.g?this.g.hB():null};
g.h.UK=function(a){this.ea()||(this.Hb("Failed to estabilish a session: "+g.Kg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&O7(this,null))};
g.h.yK=function(a){M7("Receiver availability updated: "+a);if(!this.ea()){var b=N7(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;N7(this)!=b&&this.N("yt-remote-cast2-availability-change",N7(this))}};
g.h.gB=function(){this.ea()||(this.l=P7(this),M7("Updating custom receivers: "+g.Kg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ja,(0,g.x)(function(){this.Hb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",N7(this)))};
K7.prototype.setLaunchParams=K7.prototype.vM;K7.prototype.setConnectedScreenStatus=K7.prototype.uM;K7.prototype.stopSession=K7.prototype.oN;K7.prototype.getCastSession=K7.prototype.nN;K7.prototype.requestSession=K7.prototype.requestSession;K7.prototype.init=K7.prototype.init;K7.prototype.dispose=K7.prototype.dispose;var Y7=[];f8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";g8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Je=a.hasPrevious,this.hasNext=a.hasNext,this.C=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
f8.prototype.isAdPlaying=function(){return 1081==this.playerState};
f8.prototype.getDuration=function(){return this.u?this.D+h8(this):this.D};
f8.prototype.clone=function(){return new f8(l8(this))};g.t(o8,g.P);g.h=o8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ja,w8(this,"play")):u8(this,"play"),t8(this,1,j8(p8(this))),this.N("remotePlayerChange")):r8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ja,w8(this,"pause")):u8(this,"pause"),t8(this,2,j8(p8(this))),this.N("remotePlayerChange")):r8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=p8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ja,w8(this,"seekTo",{newTime:a}))}else u8(this,"seekTo",{newTime:a});t8(this,3,a);this.N("remotePlayerChange")}else r8(this,g.Sa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ja,w8(this,"stopVideo")):u8(this,"stopVideo");var a=p8(this);a.index=-1;a.videoId="";g8(a);s8(this,a);this.N("remotePlayerChange")}else r8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=p8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){f7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Hb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){f7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Hb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);u8(this,"setVolume",e)}c.muted=b;c.volume=a;s8(this,c)}else r8(this,g.Sa(this.setVolume,a,b))};
g.h.gA=function(a,b){if(1==this.g){var c=p8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Kg(b.style),g.fc(d,c.g));u8(this,"setSubtitlesTrack",d);s8(this,c)}else r8(this,g.Sa(this.gA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();u8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=p8(this);d.audioTrackId=c;s8(this,d)}else r8(this,g.Sa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=p8(this);c=c||0;var m={videoId:a,currentIndex:c};k8(l,a,c);g.Ea(b)&&(i8(l,b),m.currentTime=b);g.Ea(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Kg(k));u8(this,"setPlaylist",m);d||s8(this,l)};
g.h.Dn=function(a,b){if(1==this.g){if(a&&b){var c=p8(this);k8(c,a,b);s8(this,c)}u8(this,"previous")}else r8(this,g.Sa(this.Dn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=p8(this);k8(c,a,b);s8(this,c)}u8(this,"next")}else r8(this,g.Sa(this.nextVideo,a,b))};
g.h.Yu=function(){1==this.g?u8(this,"dismissAutoplay"):r8(this,this.Yu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}g.P.prototype.dispose.call(this)};
g.h.U=function(){q8(this);this.o=null;this.u.clear();n8(this,null);g.P.prototype.U.call(this)};
g.h.Ys=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.rK=function(a,b){this.N(a,b)};
g.h.rI=function(a){if(!a)this.Ak(null),n8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=p8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)f7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,s8(this,b)}};
g.h.Ak=function(a){f7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),v8(this),this.N("remotePlayerChange")};
g.h.qI=function(a){a?(v8(this),this.N("remotePlayerChange")):this.Ak(null)};
g.h.Js=function(){u8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.FI=function(){var a=b8();a&&n8(this,a)};
g.h.Hb=function(a){f7("CP",a)};g.t(x8,g.P);g.h=x8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ea(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ea(k)&&(l.currentIndex=k);c&&(this.Oa.listId=c);this.Oa.videoId=d;this.Oa.index=k||0;this.Oa.state=3;i8(this.Oa,m);this.o="UNSUPPORTED";y8("Connecting with setPlaylist and params: "+g.Kg(l));this.g.connect({method:"setPlaylist",
params:g.Kg(l)},a,M5())}else y8("Connecting without params"),this.g.connect({},a,M5());Rqa(this)};
g.h.dispose=function(){this.ea()||(this.N("beforeDispose"),z8(this,3));g.P.prototype.dispose.call(this)};
g.h.U=function(){A8(this);C8(this);B8(this);g.Kp(this.C);this.C=NaN;g.Kp(this.D);this.D=NaN;this.l=null;g.Or(this.P);this.P.length=0;this.g.dispose();g.P.prototype.U.call(this);this.o=this.A=this.i=this.Oa=this.g=null};
g.h.oD=function(){this.Nh(2)};
g.h.vI=function(){y8("Channel opened");this.I&&(this.I=!1,B8(this),this.H=g.Ip((0,g.x)(function(){y8("Timing out waiting for a screen.");this.Nh(1)},this),15E3));
sqa(zqa(this.g),this.M)};
g.h.sI=function(){y8("Channel closed");isNaN(this.u)?P5(!0):P5();this.dispose()};
g.h.tI=function(a){P5();isNaN(this.Fj())?(y8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,y8("Channel error: "+a+" with reconnection in "+this.Fj()+" ms"),z8(this,2))};
g.h.uI=function(a){a.params?y8("Received: action="+a.action+", params="+g.Kg(a.params)):y8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=t5(a.params.devices);this.i=(0,g.B)(a,function(c){return new w5(c)});
a=!!g.Ya(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
F8(this,a);break;case "loungeScreenDisconnected":g.eb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
F8(this,!1);break;case "remoteConnected":var b=new w5(t5(a.params.device));g.Ya(this.i,function(c){return b?c.id==b.id:!1})||hqa(this.i,b);
break;case "remoteDisconnected":b=new w5(t5(a.params.device));g.eb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":G8(this,a);break;case "nowPlaying":Uqa(this,a);break;case "onStateChange":H8(this,a);break;case "onAdStateChange":Vqa(this,a);break;case "onVolumeChanged":Wqa(this,a);break;case "onSubtitlesTrackChanged":Tqa(this,a);break;case "nowAutoplaying":Xqa(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.A=a.params.videoId||null;this.N("autoplayUpNext",this.A);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":Yqa(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:y8("Unrecognized action: "+a.action)}};
g.h.iM=function(){if(this.l){var a=this.l;this.l=null;this.Oa.videoId!=a&&D8(this,"getNowPlaying")}};
g.h.eD=function(){var a=3;this.ea()||(a=0,isNaN(this.Fj())?Y6(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Nh=function(a){y8("Disconnecting with "+a);A8(this);this.N("beforeDisconnect",a);1==a&&P5();X6(this.g,a);this.dispose()};
g.h.dD=function(){var a=this.Oa;this.l&&(a=this.Oa.clone(),k8(a,this.l,a.index));return l8(a)};
g.h.wM=function(a){var b=new f8(a);b.videoId&&b.videoId!=this.Oa.videoId&&(this.l=b.videoId,g.Kp(this.C),this.C=g.Ip((0,g.x)(this.iM,this),5E3));var c=[];this.Oa.listId==b.listId&&this.Oa.videoId==b.videoId&&this.Oa.index==b.index||c.push("remoteQueueChange");this.Oa.playerState==b.playerState&&this.Oa.volume==b.volume&&this.Oa.muted==b.muted&&j8(this.Oa)==j8(b)&&g.Kg(this.Oa.g)==g.Kg(b.g)||c.push("remotePlayerChange");this.Oa.reset(a);(0,g.z)(c,function(d){this.N(d)},this)};
g.h.Kv=function(){var a=this.g.A.id,b=g.Ya(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Fj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.H)():NaN};
g.h.WC=function(){return this.o||"UNSUPPORTED"};
g.h.XC=function(){return this.A||""};
g.h.gN=function(){if(!isNaN(this.Fj())){var a=this.g.i;g.co(a.g);a.start()}};
g.h.pM=function(a,b){D8(this,a,b);E8(this)};
x8.prototype.subscribe=x8.prototype.subscribe;x8.prototype.unsubscribeByKey=x8.prototype.Kf;x8.prototype.getProxyState=x8.prototype.eD;x8.prototype.disconnect=x8.prototype.Nh;x8.prototype.getPlayerContextData=x8.prototype.dD;x8.prototype.setPlayerContextData=x8.prototype.wM;x8.prototype.getOtherConnectedRemoteId=x8.prototype.Kv;x8.prototype.getReconnectTimeout=x8.prototype.Fj;x8.prototype.getAutoplayMode=x8.prototype.WC;x8.prototype.getAutoplayVideoId=x8.prototype.XC;x8.prototype.reconnect=x8.prototype.gN;
x8.prototype.sendMessage=x8.prototype.pM;g.t(I8,j7);g.h=I8.prototype;g.h.Id=function(a){return this.Vc.$_gs(a)};
g.h.contains=function(a){return!!this.Vc.$_c(a)};
g.h.get=function(a){return this.Vc.$_g(a)};
g.h.start=function(){this.Vc.$_st()};
g.h.add=function(a,b,c){this.Vc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Vc.$_r(a,b,c)};
g.h.co=function(a,b,c,d){this.Vc.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.i.length;a<b;++a)this.Vc.$_ubk(this.i[a]);this.i.length=0;this.Vc=null;j7.prototype.U.call(this)};
g.h.kN=function(){this.N("screenChange")};
g.h.WJ=function(){this.N("onlineScreenChange")};
w7.prototype.$_st=w7.prototype.start;w7.prototype.$_gspc=w7.prototype.lN;w7.prototype.$_gsppc=w7.prototype.fB;w7.prototype.$_c=w7.prototype.contains;w7.prototype.$_g=w7.prototype.get;w7.prototype.$_a=w7.prototype.add;w7.prototype.$_un=w7.prototype.co;w7.prototype.$_r=w7.prototype.remove;w7.prototype.$_gs=w7.prototype.Id;w7.prototype.$_gos=w7.prototype.eB;w7.prototype.$_s=w7.prototype.subscribe;w7.prototype.$_ubk=w7.prototype.Kf;var d9=null,c9=!1,J8=null,K8=null,$8=null,O8=[];g.t(e9,g.D);g.h=e9.prototype;
g.h.U=function(){g.D.prototype.U.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.Qy,this);this.g.unsubscribe("remotePlayerChange",this.Ck,this);this.g.unsubscribe("remoteQueueChange",this.xn,this);this.g.unsubscribe("autoplayUpNext",this.ty,this);this.g.unsubscribe("previousNextChange",this.Ny,this);this.g.unsubscribe("nowAutoplaying",this.Jy,this);this.g.unsubscribe("autoplayDismissed",this.ry,this);this.g=this.u=null};
g.h.nx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(i9(this)){if(!p8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==p8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Nj(c[0],c[1]);break;case "control_subtitles_set_track":j9(this,c[0]);break;case "control_set_audio_track":c=c[0],i9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();k9(this,0==c?void 0:c);break;case "control_seek":k9(this,c[0]);break;case "control_subtitles_set_track":j9(this,c[0]);break;case "control_set_audio_track":c=c[0],i9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.pI=function(a){this.I.kD(a)};
g.h.RM=function(a){this.nx("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.tA=function(){var a=this.i.getOption("captions","track");g.Yb(a)||j9(this,a)};
g.h.Fy=function(a){if(i9(this)){this.g.unsubscribe("remotePlayerChange",this.Ck,this);var b=Math.round(a.volume);a=!!a.muted;var c=p8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.Ck,this)}};
g.h.qJ=function(){g.Yb(this.C)||l9(this,this.C);this.D=!1};
g.h.Qy=function(a,b){this.A.stop();2==b&&this.sA()};
g.h.Ck=function(){if(i9(this)){this.o.stop();var a=p8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Km=1;break;case 1082:case 1083:this.u.Km=0;break;default:this.u.Km=-1}switch(a.playerState){case 1081:case 1:g9(this,new g.iC(8));this.rA();break;case 1085:case 3:g9(this,new g.iC(9));break;case 1083:case 0:g9(this,new g.iC(2));this.H.stop();f9(this,this.i.getVideoData().lengthSeconds);break;case 1084:g9(this,new g.iC(4));break;case 2:g9(this,new g.iC(4));f9(this,j8(a));
break;case -1:g9(this,new g.iC(64));break;case -1E3:g9(this,new g.iC(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=p8(this.g).g;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,l9(this,a));a=p8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.RA()}else h9(this)};
g.h.Ny=function(){this.i.N("mdxpreviousnextchange")};
g.h.xn=function(){i9(this)||h9(this)};
g.h.qC=function(){this.g.Yu()};
g.h.ty=function(a){a&&(a=g.Fq("/watch_queue_ajax",{method:"GET",Dc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.wL,this)}))&&(this.M=(0,g.x)(a.abort,a))};
g.h.wL=function(a,b){var c=new g.VA(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.Jy=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.ry=function(){this.i.N("mdxautoplaycanceled")};
g.h.MF=function(a,b){-1==p8(this.g).playerState?k9(this,a):b&&this.g.seekTo(a)};
g.h.RA=function(){if(i9(this)){var a=p8(this.g);this.l.Ka(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.Fy)}};
g.h.rA=function(){this.o.stop();if(!this.g.ea()){var a=p8(this.g);1==a.playerState&&g9(this,new g.iC(8));f9(this,j8(a));this.o.start()}};
g.h.sA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(n9,g.W);n9.prototype.o=function(){v5("mdx-privacy-popup-cancel");this.l.hide()};
n9.prototype.A=function(){v5("mdx-privacy-popup-confirm");this.l.hide()};g.t(p9,g.W);p9.prototype.u=function(a){o9(this,a.state)};g.t(q9,g.DT);q9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.ub(a,this.A,this),g.ET(this,(0,g.B)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.se(this.A(a)),this.enable(!0)):this.enable(!1)};
q9.prototype.A=function(a){return a.key};
q9.prototype.re=function(a){return"cast-selector-receiver"==a?"Cast...":this.F[a].name};
q9.prototype.Ic=function(a){g.DT.prototype.Ic.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.ib()};g.t(r9,g.yK);g.h=r9.prototype;
g.h.create=function(){cra(g.Fy(g.X(this.player)));this.o.push(g.Pp("yt-remote-before-disconnect",this.mI,this));this.o.push(g.Pp("yt-remote-connection-change",this.zK,this));this.o.push(g.Pp("yt-remote-receiver-availability-change",this.Oy,this));this.o.push(g.Pp("yt-remote-auto-connect",this.xK,this));this.o.push(g.Pp("yt-remote-receiver-resumed",this.wK,this));this.o.push(g.Pp("mdx-privacy-popup-confirm",this.YL,this));this.o.push(g.Pp("mdx-privacy-popup-cancel",this.XL,this));this.Oy()};
g.h.load=function(){this.player.cancelPlayback();g.yK.prototype.load.call(this);this.u=new e9(this,this.player,this.g);var a=(a=b9())?a.currentTime:0;var b=Z8()?new o8(U8(),void 0):null;0==a&&b&&(a=j8(p8(b)));0!=a&&this.Kc(a);m9(this,this.kk,this.kk);g.DX(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.rf(this.u,this.g);this.g=this.u=null;g.yK.prototype.unload.call(this);g.DX(this.player.app,5)};
g.h.U=function(){g.Qp(this.o);g.yK.prototype.U.call(this)};
g.h.Xe=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.nx.apply(this.u,[a].concat(g.fa(c)))};
g.h.getAdState=function(){return this.Km};
g.h.gD=function(){return this.loaded?this.u.suggestion:null};
g.h.Je=function(){return this.g?p8(this.g).Je:!1};
g.h.hasNext=function(){return this.g?p8(this.g).hasNext:!1};
g.h.Kc=function(a,b){this.H=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.H};
g.h.getProgressState=function(){var a=p8(this.g),b=this.player.getVideoData();return{allowSeeking:g.Q(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.dc():!a.isAdPlaying()&&this.player.dc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+h8(a):a.l,isAtLiveHead:1>=(a.u?a.i+h8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+h8(a):a.i,seekableStart:0<a.o?a.o+
h8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.Dn=function(){this.g&&this.g.Dn()};
g.h.mI=function(a){1==a&&(this.C=this.g?p8(this.g):null)};
g.h.zK=function(){var a=Z8()?new o8(U8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.C=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.qf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.C)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,j8(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Oy=function(){this.A=[this.i].concat(dra());var a=V8()||this.i;s9(this,a);this.player.la("onMdxReceiversChange")};
g.h.xK=function(){var a=V8();s9(this,a)};
g.h.wK=function(){this.l=V8()};
g.h.YL=function(){this.D=!0;c9=!1;d9&&X8(d9,1);d9=null};
g.h.XL=function(){this.D=!1;s9(this,this.i);this.l=this.i;c9=!1;d9=null;this.player.playVideo()};
g.h.xc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?d8():s9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&d8(),!0):!1}};
g.h.Js=function(){this.g.Js()};
g.h.Lb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.UU.remote=r9;})(_yt_player);
